name: neumorphic_calculator
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  math_expressions: ^2.5.0
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  day_night_themed_switch: ^1.0.0
  auto_size_text_field: ^2.2.3
  animated_theme_switcher:
    git: https://github.com/mllrr96/animated_theme_switcher.git
  equatable: ^2.0.5
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  fraction: ^5.0.2
  timeago: ^3.7.0
  flutter_bloc: ^8.1.6
  injectable: ^2.4.2
  logger: ^2.4.0
  flutter_slidable: ^3.1.1
  tutorial_coach_mark: ^1.2.11
  lottie: ^3.1.2
  system_theme: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: 
  injectable_generator:  
flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/lottie/


  fonts:
    - family: CalculatorIcons
      fonts:
        - asset: assets/fonts/CalculatorIcons.ttf


